const CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vQAFcBJvDUqxyx0xJmsqoGjG1XCbX8zNUory4qCmndR0gjxQSwQhtGN8OFk9uB8Co2VkD9AdsyOHFKX/pub?gid=638479938&single=true&output=csv';
// ใส่ Apps Script Web App URL ที่ deploy แล้วตรงนี้เพื่อเปิด CRUD
const API_URL='';
const cols=['ที่','เดือน','OP visit','NCD visit','Non NCD visit','Bed rate','Active bed','Sum AdjRW','CMI','Fixed cost','LC(OT)','ยอดพิจารณาจ่าย IP','อัตราจ่าย/Adj.','หักเงินเดือน','คงเหลือรับ','ผู้รายงาน','วันที่รายงาน'];
const crudCols=cols.slice(1);
const numericCols=['OP visit','NCD visit','Non NCD visit','Bed rate','Active bed','Sum AdjRW','CMI','Fixed cost','LC(OT)','ยอดพิจารณาจ่าย IP','อัตราจ่าย/Adj.','หักเงินเดือน','คงเหลือรับ'];
const monthNames=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
const money=new Intl.NumberFormat('th-TH',{maximumFractionDigits:2}); const integer=new Intl.NumberFormat('th-TH',{maximumFractionDigits:0});
let rows=[],trendChart,visitChart,changeChart,metricChart,editingIndex=null;
const $=id=>document.getElementById(id); const n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null};
function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nx=text[i+1];if(c==='"'&&q&&nx==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()!==''))out.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}
function parseRows(text){const a=parseCSV(text),h=a[0]||[];return a.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()]))).filter(r=>r['เดือน']);}
function thaiYear(r){const m=(r['เดือน']||'').match(/(25\d{2}|20\d{2})$/);return m?m[1]:''} function monthIndex(s){return monthNames.findIndex(x=>(s||'').startsWith(x));}
function sortRows(a){return [...a].sort((x,y)=>{const k=(thaiYear(x)||'0000')+'-'+String(monthIndex(x['เดือน'])).padStart(2,'0');const l=(thaiYear(y)||'0000')+'-'+String(monthIndex(y['เดือน'])).padStart(2,'0');return k.localeCompare(l)});}
function sum(d,k){return d.reduce((s,r)=>s+(n(r[k])||0),0)} function avg(d,k){return d.length?sum(d,k)/d.length:0} function pct(a,b){return b===0?(a===0?0:null):((a-b)/Math.abs(b))*100}
function fmt(v,k){if(v==null||v==='')return '—';return numericCols.includes(k)?money.format(n(v)):v}
async function load(){setStatus('กำลังโหลดข้อมูล...');const res=await fetch(CSV_URL,{cache:'no-store'});if(!res.ok)throw new Error('โหลดข้อมูล Google Sheet ไม่สำเร็จ');rows=sortRows(parseRows(await res.text()));initFilters();render();setStatus(`โหลดข้อมูลแล้ว ${rows.length} รายการ • อัปเดตจาก Published CSV`)}
function initFilters(){const years=[...new Set(rows.map(thaiYear).filter(Boolean))].sort((a,b)=>Number(a)-Number(b));$('yearFilter').innerHTML='<option value="all">ทุกปี</option>'+years.map(y=>`<option>${y}</option>`).join('');$('monthFilter').innerHTML='<option value="all">ทุกเดือน</option>'+monthNames.map(x=>`<option>${x}</option>`).join('');$('metricFilter').innerHTML=numericCols.map(x=>`<option value="${x}">${x}</option>`).join('');}
function filtered(){const y=$('yearFilter').value,m=$('monthFilter').value,q=$('search').value.trim().toLowerCase();return sortRows(rows.filter(r=>(y==='all'||thaiYear(r)===y)&&(m==='all'||(r['เดือน']||'').startsWith(m))&&(!q||Object.values(r).join(' ').toLowerCase().includes(q))));}
function render(){const d=filtered();$('count').textContent=`${d.length} รายการ`;renderKPI(d);renderCharts(d);renderRank(d);renderAnalysis(d);renderTable(d)}
function renderKPI(d){const latest=d[d.length-1],previous=d.length>1?d[d.length-2]:null;const cards=[['OP visit',sum(d,'OP visit'),'ครั้ง'],['NCD visit',sum(d,'NCD visit'),'ครั้ง'],['Non NCD visit',sum(d,'Non NCD visit'),'ครั้ง'],['คงเหลือรับ',sum(d,'คงเหลือรับ'),'บาท'],['Bed rate',avg(d,'Bed rate'),'%'],['CMI',avg(d,'CMI'),'เฉลี่ย']];$('kpis').innerHTML=cards.map(([k,v,u])=>{const pv=previous?n(previous[k]):null;const lv=latest?n(latest[k]):null;const ch=pct(lv,pv);return `<div class="col-6 col-xl-2"><div class="card shadow-sm kpi"><div class="card-body"><div class="label">${k}</div><div class="value">${money.format(v)}</div><div class="sub">${u}${ch==null?'':` • เดือนล่าสุด ${ch>=0?'+':''}${ch.toFixed(1)}%`}</div></div></div></div>`}).join('')}
function renderCharts(d){const labels=d.map(x=>x['เดือน']);const vals=k=>d.map(x=>n(x[k])||0);trendChart?.destroy();visitChart?.destroy();const metric=$('metricFilter').value;trendChart=new Chart($('trendChart'),{type:'line',data:{labels,datasets:[{label:metric,data:vals(metric),tension:.25}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{ticks:{maxRotation:60,minRotation:20}}}}});visitChart=new Chart($('visitChart'),{type:'bar',data:{labels:['OP visit','NCD visit','Non NCD visit'],datasets:[{label:'รวม',data:[sum(d,'OP visit'),sum(d,'NCD visit'),sum(d,'Non NCD visit')]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}})}
function renderRank(d){const metric=$('metricFilter').value;const scored=d.map(r=>({...r,_v:n(r[metric])||0})).sort((a,b)=>b._v-a._v);const make=a=>a.slice(0,5).map((r,i)=>`<div class="rank-row"><span>${i+1}. ${r['เดือน']}</span><b>${money.format(r._v)}</b></div>`).join('')||'<div class="small-note">ไม่มีข้อมูล</div>';$('topTable').innerHTML=make(scored);$('bottomTable').innerHTML=make([...scored].reverse())}
function renderAnalysis(d){const metric=$('metricFilter').value;const years=[...new Set(d.map(thaiYear).filter(Boolean))].sort((a,b)=>Number(a)-Number(b));let html='<thead><tr><th>ปี</th><th>จำนวนเดือน</th><th>OP visit</th><th>NCD visit</th><th>Non NCD</th><th>คงเหลือรับ</th><th>Bed rate เฉลี่ย</th><th>CMI เฉลี่ย</th><th>เปลี่ยนแปลง '+metric+'</th></tr></thead><tbody>';let prev=null;for(const y of years){const yd=d.filter(r=>thaiYear(r)===y),v=sum(yd,metric),ch=pct(v,prev);html+=`<tr><td>${y}</td><td>${yd.length}</td><td>${integer.format(sum(yd,'OP visit'))}</td><td>${integer.format(sum(yd,'NCD visit'))}</td><td>${integer.format(sum(yd,'Non NCD visit'))}</td><td>${money.format(sum(yd,'คงเหลือรับ'))}</td><td>${money.format(avg(yd,'Bed rate'))}</td><td>${money.format(avg(yd,'CMI'))}</td><td class="${ch>0?'delta-up':ch<0?'delta-down':'delta-flat'}">${ch==null?'—':`${ch>=0?'+':''}${ch.toFixed(1)}%`}</td></tr>`;prev=v}html+='</tbody>';$('yearTable').innerHTML=html;const latest=d[d.length-1],prevM=d.length>1?d[d.length-2]:null;const ch=pct(n(latest?.[metric]),n(prevM?.[metric]));$('analysisCards').innerHTML=[['ตัวชี้วัด',metric],['เดือนล่าสุด',latest?.['เดือน']||'—'],['ค่าเดือนล่าสุด',money.format(n(latest?.[metric])||0)],['เทียบเดือนก่อน',ch==null?'—':`${ch>=0?'+':''}${ch.toFixed(1)}%`]].map(x=>`<div class="col-6 col-xl-3"><div class="card shadow-sm kpi"><div class="card-body"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div></div></div>`).join('');changeChart?.destroy();metricChart?.destroy();changeChart=new Chart($('changeChart'),{type:'bar',data:{labels:d.map(x=>x['เดือน']),datasets:[{label:'% เปลี่ยนแปลงจากเดือนก่อน',data:d.map((r,i)=>i?pct(n(r[metric]),n(d[i-1][metric])):0)}]},options:{responsive:true,maintainAspectRatio:false}});metricChart=new Chart($('metricChart'),{type:'line',data:{labels:d.map(x=>x['เดือน']),datasets:[{label:metric,data:d.map(x=>n(x[metric])||0),tension:.25}]},options:{responsive:true,maintainAspectRatio:false}})}
function renderTable(d){$('dataTable').innerHTML='<thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'<th>จัดการ</th></tr></thead><tbody>'+d.map(r=>{const idx=rows.indexOf(r);return '<tr>'+cols.map(c=>`<td>${fmt(r[c],c)}</td>`).join('')+`<td><button class="btn btn-sm btn-outline-primary me-1" onclick="editRow(${idx})">แก้ไข</button><button class="btn btn-sm btn-outline-danger" onclick="deleteRow(${idx})">ลบ</button></td></tr>`}).join('')+'</tbody>'}
function buildForm(r={}){$('formGrid').innerHTML=crudCols.map((c,i)=>`<div class="col-12 col-md-6"><label class="form-label small fw-bold">${c}</label><input class="form-control" data-field="${c}" value="${String(r[c]??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"></div>`).join('')}
function openModal(idx=null){editingIndex=idx;$('modalTitle').textContent=idx==null?'เพิ่มข้อมูล':'แก้ไขข้อมูล';buildForm(idx==null?{}:rows[idx]);new bootstrap.Modal($('rowModal')).show()}
async function saveRow(){if(!API_URL){alert('ยังไม่ได้ตั้งค่า Apps Script Web App URL ใน app.js (ตัวแปร API_URL)');return}const obj=Object.fromEntries([...document.querySelectorAll('#formGrid [data-field]')].map(x=>[x.dataset.field,x.value]));const action=editingIndex==null?'append':'update';const payload={action,values:crudCols.map(c=>obj[c]||'')};if(editingIndex!=null)payload.row=editingIndex+2;setStatus('กำลังบันทึก...');const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const out=await res.json();if(!out.ok)throw new Error(out.error||'บันทึกไม่สำเร็จ');bootstrap.Modal.getInstance($('rowModal')).hide();await load();setStatus('บันทึกข้อมูลสำเร็จ')}
async function deleteRow(idx){if(!API_URL){alert('ยังไม่ได้ตั้งค่า Apps Script Web App URL ใน app.js');return}if(!confirm(`ยืนยันลบรายการ “${rows[idx]['เดือน']}” ?`))return;setStatus('กำลังลบ...');const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'delete',row:idx+2})});const out=await res.json();if(!out.ok)throw new Error(out.error||'ลบไม่สำเร็จ');await load();setStatus('ลบข้อมูลสำเร็จ')}
function setStatus(t){$('status').textContent=t} window.editRow=openModal;window.deleteRow=deleteRow;
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');['dashboard','analysis','data'].forEach(v=>$('view-'+v).classList.toggle('d-none',v!==b.dataset.view))});['yearFilter','monthFilter','search','metricFilter'].forEach(id=>$(id).addEventListener('input',render));$('refresh').onclick=()=>load().catch(e=>setStatus(e.message));$('reset').onclick=()=>{$('yearFilter').value='all';$('monthFilter').value='all';$('search').value='';render()};$('addBtn').onclick=()=>openModal();$('saveBtn').onclick=()=>saveRow().catch(e=>alert(e.message));load().catch(e=>setStatus(e.message));
